# Generated by Django 5.1.6 on 2025-02-12 22:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BG", "Begginer"),
                            ("EX", "Experienced"),
                            ("EP", "Expert"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("CPP", "C++"),
                            ("JS", "Javascript"),
                            ("PY", "Python"),
                            ("JAVA", "Java"),
                            ("LUA", "Lua"),
                            ("RS", "Rust"),
                            ("GO", "Go"),
                            ("JL", "Julia"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(14),
                        ]
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("residence", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.skill"
                    ),
                ),
            ],
        ),
    ]
