# Generated by Django 5.1.6 on 2025-02-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="skills",
        ),
        migrations.AddField(
            model_name="developer",
            name="skills",
            field=models.ManyToManyField(blank=True, to="users.skill"),
        ),
    ]
