# Generated by Django 5.1.6 on 2025-02-12 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_developer_skills_developer_skills"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="developer",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="developer",
            name="residence",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="developer",
            constraint=models.CheckConstraint(
                condition=models.Q(("age__gte", 14)), name="old_enough"
            ),
        ),
    ]
