# Generated by Django 5.1.6 on 2025-02-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_developer_age_alter_developer_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="dev_skills",
                related_query_name="dev_skill",
                to="users.skill",
            ),
        ),
    ]
