# Generated by Django 5.1.6 on 2025-02-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
