# Generated by Django 5.1.6 on 2025-02-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="open_positions",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
