# Generated by Django 5.1.6 on 2025-02-13 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_project_apllied_collaborators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="apllied_collaborators",
        ),
        migrations.AddField(
            model_name="project",
            name="apllied_collaborators",
            field=models.ManyToManyField(
                related_name="apllied_collaborators", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
