# Generated by Django 5.1.6 on 2025-02-13 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_project_apllied_collaborators_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="apllied_collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="apllied_collaborators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
